
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run: docker images -a
      - run: docker-compose --verbose build
      - run: docker-compose --verbose build --no-cache
      - run: docker image -a